<?php
namespace Anorm\GraphQL\Tools\Writer;

/** Small pieces every writer needs. */
class Php
{
    const HEADER = '// GENERATED by anorm-graphql';

    const TYPE_CALLS = array(
        'ID' => 'Type::id()',
        'Int' => 'Type::int()',
        'Float' => 'Type::float()',
        'Boolean' => 'Type::boolean()',
        'String' => 'Type::string()',
    );

    /** @return string e.g. 'App\GraphQL\Type\Client' */
    public static function entityNamespace($typeNamespace, $entity)
    {
        return \trim($typeNamespace, '\\') . '\\' . $entity;
    }

    /** @return string e.g. "'name 1'" */
    public static function export($value)
    {
        return \var_export($value, true);
    }
}
