<?php

namespace Anorm\GraphQL\Test\Tools;

use Anorm\GraphQL\Tools\FileWriter;
use Anorm\GraphQL\Test\TempDir;
use PHPUnit\Framework\TestCase;

class FileWriterTest extends TestCase
{
    use TempDir;

    private const GENERATED = "<?php\n\n// GENERATED by anorm-graphql — do not edit.\n";

    protected function setUp(): void
    {
        $this->makeTempDir();
    }

    protected function tearDown(): void
    {
        $this->removeTempDir();
    }

    public function testGeneratedFileIsCreatedWithItsDirectories(): void
    {
        $writer = new FileWriter();
        $this->assertTrue($writer->writeGenerated("$this->dir/a/Base/X.php", self::GENERATED . 'one'));
        $this->assertSame(self::GENERATED . 'one', file_get_contents("$this->dir/a/Base/X.php"));
        $this->assertStringStartsWith('written', $writer->report[0]);
    }

    public function testGeneratedFileIsOverwrittenWhenItCarriesTheHeader(): void
    {
        $writer = new FileWriter();
        $writer->writeGenerated("$this->dir/X.php", self::GENERATED . 'one');
        $writer->writeGenerated("$this->dir/X.php", self::GENERATED . 'two');
        $this->assertSame(self::GENERATED . 'two', file_get_contents("$this->dir/X.php"));
    }

    public function testAHandWrittenFileInTheWayIsRefused(): void
    {
        file_put_contents("$this->dir/X.php", "<?php\n// mine\n");
        $writer = new FileWriter();
        $this->assertFalse($writer->writeGenerated("$this->dir/X.php", self::GENERATED));
        $this->assertSame("<?php\n// mine\n", file_get_contents("$this->dir/X.php"));
        $this->assertStringStartsWith('refused', $writer->report[0]);
    }

    public function testUnchangedGeneratedFileIsReportedCurrent(): void
    {
        $writer = new FileWriter();
        $writer->writeGenerated("$this->dir/X.php", self::GENERATED);
        $writer->writeGenerated("$this->dir/X.php", self::GENERATED);
        $this->assertStringStartsWith('current', $writer->report[1]);
    }

    public function testOnceOnlyFileIsKeptUnlessForced(): void
    {
        $writer = new FileWriter();
        $writer->writeOnce("$this->dir/Y.php", 'first');
        $writer->writeOnce("$this->dir/Y.php", 'second');
        $this->assertSame('first', file_get_contents("$this->dir/Y.php"));
        $this->assertStringStartsWith('kept', $writer->report[1]);

        $writer->writeOnce("$this->dir/Y.php", 'third', true);
        $this->assertSame('third', file_get_contents("$this->dir/Y.php"));
        $this->assertStringStartsWith('forced', $writer->report[2]);
    }

    public function testDryRunWritesNothingButReports(): void
    {
        $writer = new FileWriter(true);
        $writer->writeGenerated("$this->dir/sub/X.php", self::GENERATED);
        $writer->writeOnce("$this->dir/Y.php", 'first');
        $this->assertFileDoesNotExist("$this->dir/sub/X.php");
        $this->assertFileDoesNotExist("$this->dir/Y.php");
        $this->assertCount(2, $writer->report);
        $this->assertStringContainsString('(dry run)', $writer->report[0]);
    }
}
