<?php

namespace Anorm\GraphQL\Test\Tools;

use Anorm\GraphQL\Tools\FileWriter;
use Anorm\GraphQL\Test\TempDir;
use PHPUnit\Framework\TestCase;

class FileWriterTest extends TestCase
{
    use TempDir;

    private const GENERATED = "<?php\n\n// GENERATED by anorm-graphql — do not edit.\n";

    protected function setUp(): void
    {
        $this->makeTempDir();
    }

    protected function tearDown(): void
    {
        $this->removeTempDir();
    }

    public function testGeneratedFileIsCreatedWithItsDirectories(): void
    {
        $writer = new FileWriter();
        $this->assertTrue($writer->writeGenerated("$this->dir/a/Base/X.php", self::GENERATED . 'one'));
        $this->assertSame(self::GENERATED . 'one', file_get_contents("$this->dir/a/Base/X.php"));
        $this->assertStringStartsWith('written', $writer->report[0]);
    }

    public function testGeneratedFileIsOverwrittenWhenItCarriesTheHeader(): void
    {
        $writer = new FileWriter();
        $writer->writeGenerated("$this->dir/X.php", self::GENERATED . 'one');
        $writer->writeGenerated("$this->dir/X.php", self::GENERATED . 'two');
        $this->assertSame(self::GENERATED . 'two', file_get_contents("$this->dir/X.php"));
    }

    public function testAHandWrittenFileInTheWayIsRefused(): void
    {
        file_put_contents("$this->dir/X.php", "<?php\n// mine\n");
        $writer = new FileWriter();
        $this->assertFalse($writer->writeGenerated("$this->dir/X.php", self::GENERATED));
        $this->assertSame("<?php\n// mine\n", file_get_contents("$this->dir/X.php"));
        $this->assertStringStartsWith('refused', $writer->report[0]);
    }

    public function testAFileThatOnlyMentionsTheHeaderIsSomebodysOwn(): void
    {
        $mine = "<?php\n\n// My own base class. Not to be confused with files marked\n"
            . "// GENERATED by anorm-graphql, which this is not.\nclass X {}\n";
        file_put_contents("$this->dir/X.php", $mine);
        $writer = new FileWriter();
        $this->assertFalse($writer->writeGenerated("$this->dir/X.php", self::GENERATED));
        $this->assertSame($mine, file_get_contents("$this->dir/X.php"));
        $this->assertStringStartsWith('refused', $writer->report[0]);
    }

    public function testNothingIsWrittenThroughASymbolicLink(): void
    {
        $outside = "$this->dir/outside.php";
        file_put_contents($outside, self::GENERATED . 'precious');
        mkdir("$this->dir/out");
        symlink($outside, "$this->dir/out/X.php");

        $writer = new FileWriter(false, ["$this->dir/out"]);
        $this->assertFalse($writer->writeGenerated("$this->dir/out/X.php", self::GENERATED . 'clobbered'));
        $writer->writeOnce("$this->dir/out/X.php", 'clobbered', true);
        $writer->replace("$this->dir/out/X.php", 'clobbered', 'updated');
        $this->assertSame(self::GENERATED . 'precious', file_get_contents($outside));
        $this->assertCount(3, $writer->report);
        foreach ($writer->report as $line) {
            $this->assertStringContainsString('symbolic link', $line);
        }
    }

    public function testNothingIsWrittenOutsideTheDirectoriesGiven(): void
    {
        mkdir("$this->dir/out");
        mkdir("$this->dir/elsewhere");
        symlink("$this->dir/elsewhere", "$this->dir/out/Linked");

        $writer = new FileWriter(false, ["$this->dir/out"]);
        $this->assertFalse($writer->writeGenerated("$this->dir/out/Linked/Base/X.php", self::GENERATED));
        $this->assertFalse($writer->writeGenerated("$this->dir/out/../escaped.php", self::GENERATED));
        $this->assertTrue($writer->writeGenerated("$this->dir/out/Fine/Base/X.php", self::GENERATED));
        $this->assertDirectoryDoesNotExist("$this->dir/elsewhere/Base");
        $this->assertFileDoesNotExist("$this->dir/escaped.php");
        $this->assertStringContainsString('outside the directories given', $writer->report[0]);
    }

    public function testAGivenDirectoryMayItselfBeASymbolicLink(): void
    {
        mkdir("$this->dir/real");
        symlink("$this->dir/real", "$this->dir/out");
        $writer = new FileWriter(false, ["$this->dir/out"]);
        $this->assertTrue($writer->writeGenerated("$this->dir/out/A/Base/X.php", self::GENERATED));
        $this->assertFileExists("$this->dir/real/A/Base/X.php");
    }

    public function testUnchangedGeneratedFileIsReportedCurrent(): void
    {
        $writer = new FileWriter();
        $writer->writeGenerated("$this->dir/X.php", self::GENERATED);
        $writer->writeGenerated("$this->dir/X.php", self::GENERATED);
        $this->assertStringStartsWith('current', $writer->report[1]);
    }

    public function testOnceOnlyFileIsKeptUnlessForced(): void
    {
        $writer = new FileWriter();
        $writer->writeOnce("$this->dir/Y.php", 'first');
        $writer->writeOnce("$this->dir/Y.php", 'second');
        $this->assertSame('first', file_get_contents("$this->dir/Y.php"));
        $this->assertStringStartsWith('kept', $writer->report[1]);

        $writer->writeOnce("$this->dir/Y.php", 'third', true);
        $this->assertSame('third', file_get_contents("$this->dir/Y.php"));
        $this->assertStringStartsWith('forced', $writer->report[2]);
    }

    public function testDryRunWritesNothingButReports(): void
    {
        $writer = new FileWriter(true);
        $writer->writeGenerated("$this->dir/sub/X.php", self::GENERATED);
        $writer->writeOnce("$this->dir/Y.php", 'first');
        $this->assertFileDoesNotExist("$this->dir/sub/X.php");
        $this->assertFileDoesNotExist("$this->dir/Y.php");
        $this->assertCount(2, $writer->report);
        $this->assertStringContainsString('(dry run)', $writer->report[0]);
    }
}
