<?php

namespace Anorm\GraphQL\Test\Tools;

use Anorm\GraphQL\Test\Fixtures\Model\WidgetModel;
use Anorm\GraphQL\Tools\NullPdo;
use Anorm\GraphQL\Tools\TypeInfo;
use Anorm\GraphQL\Tools\TypeInfoBuilder;
use Anorm\GraphQL\Tools\Writer\InputBaseWriter;
use Anorm\GraphQL\Tools\Writer\InputWriter;
use Anorm\GraphQL\Tools\Writer\TestCaseWriter;
use Anorm\GraphQL\Tools\Writer\TestWriter;
use Anorm\GraphQL\Tools\Writer\TypeBaseWriter;
use Anorm\GraphQL\Tools\Writer\TypeWriter;
use PHPUnit\Framework\TestCase;

/**
 * Each writer against a golden file. To accept an intended change, run with
 * UPDATE_GOLDEN=1 and review the diff of test/Fixtures/golden in git.
 */
class WritersTest extends TestCase
{
    private function info(bool $readOnly = false): TypeInfo
    {
        return (new TypeInfoBuilder())->build(new WidgetModel(new NullPdo()), $readOnly);
    }

    private function assertGolden(string $name, string $actual): void
    {
        $path = __DIR__ . '/../Fixtures/golden/' . $name . '.txt';
        if (getenv('UPDATE_GOLDEN')) {
            file_put_contents($path, $actual);
        }
        $this->assertFileExists($path);
        $this->assertSame(file_get_contents($path), $actual, "$name differs from its golden file");
        $this->assertValidPhp($actual, $name);
    }

    private function assertValidPhp(string $code, string $name): void
    {
        try {
            $this->assertNotEmpty(token_get_all($code, TOKEN_PARSE));
        } catch (\ParseError $e) {
            $this->fail("$name is not valid PHP: " . $e->getMessage());
        }
    }

    public function testTypeBase(): void
    {
        $this->assertGolden('WidgetTypeBase', (new TypeBaseWriter())->render($this->info(), 'App\GraphQL\Type'));
    }

    public function testInputBase(): void
    {
        $this->assertGolden('WidgetInputBase', (new InputBaseWriter())->render($this->info(), 'App\GraphQL\Type'));
    }

    public function testType(): void
    {
        $this->assertGolden('WidgetType', (new TypeWriter())->render($this->info(), 'App\GraphQL\Type'));
    }

    public function testInput(): void
    {
        $this->assertGolden('WidgetInput', (new InputWriter())->render($this->info(), 'App\GraphQL\Type'));
    }

    public function testTest(): void
    {
        $this->assertGolden('WidgetTypeTest', (new TestWriter())->render($this->info(), 'App\GraphQL\Type', 'Tests\GraphQL'));
    }

    public function testReadOnlyTestHasNoInput(): void
    {
        $code = (new TestWriter())->render($this->info(true), 'App\GraphQL\Type', 'Tests\GraphQL');
        $this->assertStringContainsString('return null;', $code);
        $this->assertStringNotContainsString('WidgetInput', $code);
        $this->assertValidPhp($code, 'read-only test');
    }

    public function testAnEntityWithOnlyBooleansStillGetsSomethingToUpdate(): void
    {
        $model = new \Anorm\GraphQL\Test\Fixtures\AwkwardModel\FlagModel(new NullPdo());
        $code = (new TestWriter())->render((new TypeInfoBuilder())->build($model), 'App\GraphQL\Type', 'Tests\GraphQL');
        // Created as true, updated to false: an empty sampleUpdate() would skip the update step unnoticed.
        $this->assertMatchesRegularExpression("/function sampleUpdate\(\): array\s+\{\s+return \[\s+'active' => false,\s+\];/", $code);
        $this->assertValidPhp($code, 'Boolean-only test');
    }

    public function testAnEntityOfNothingButKeysSaysItsUpdateIsNotTested(): void
    {
        $model = new \Anorm\GraphQL\Test\Fixtures\AwkwardModel\LinkModel(new NullPdo());
        $code = (new TestWriter())->render((new TypeInfoBuilder())->build($model), 'App\GraphQL\Type', 'Tests\GraphQL');
        $this->assertStringContainsString('// Nothing to update could be chosen: every field is the key or a foreign key.', $code);
        $this->assertStringContainsString('the test reports itself incomplete', $code);
        $this->assertStringContainsString('add: ownerId, widgetId', $code);
        $this->assertValidPhp($code, 'keys-only test');
    }

    public function testAnUpdateFieldThatIsNotABooleanIsPreferred(): void
    {
        $code = (new TestWriter())->render($this->info(), 'App\GraphQL\Type', 'Tests\GraphQL');
        $this->assertMatchesRegularExpression("/function sampleUpdate\(\): array\s+\{\s+return \[\s+'name' => 'name 2',\s+\];/", $code);
    }

    public function testTestCase(): void
    {
        $this->assertGolden('TestCase', (new TestCaseWriter())->render('Tests\GraphQL', 'App\GraphQL\ApiSchema'));
    }

    public function testBaseFilesCarryTheGeneratedHeaderAndOnceOnlyFilesDoNot(): void
    {
        $header = '// GENERATED by anorm-graphql';
        $this->assertStringContainsString($header, (new TypeBaseWriter())->render($this->info(), 'A'));
        $this->assertStringContainsString($header, (new InputBaseWriter())->render($this->info(), 'A'));
        $this->assertStringNotContainsString($header, (new TypeWriter())->render($this->info(), 'A'));
        $this->assertStringNotContainsString($header, (new InputWriter())->render($this->info(), 'A'));
    }
}
